# Generated by Django 4.2.23 on 2025-10-28 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("venue", models.CharField(max_length=200)),
                ("max_capacity", models.IntegerField(default=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("student_id", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("qr_code_data", models.TextField(unique=True)),
                ("qr_code_image", models.TextField(blank=True)),
                ("is_valid", models.BooleanField(default=True)),
                ("has_attended", models.BooleanField(default=False)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("scanned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-registered_at"],
                "unique_together": {("event", "email")},
            },
        ),
        migrations.CreateModel(
            name="AttendanceLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scan_time", models.DateTimeField(auto_now_add=True)),
                (
                    "scan_result",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("already_used", "Already Used"),
                            ("invalid", "Invalid"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_logs",
                        to="events.registration",
                    ),
                ),
            ],
            options={
                "ordering": ["-scan_time"],
            },
        ),
    ]
